Repository MentorMate/create-vue, pull requests merged in 2023-10, with the labels that each got.

#8 Update README.md
  README.md
Labels: documentation

#7 Update package.json & remove unused files
  .github/workflows/build-and-publish.yml
  .github/workflows/ci.yml
  .github/workflows/main.yml
  .gitignore
  .gitmodules
  .npmrc
  package-lock.json
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: enhancement, invalid

#14 Add i18n support
  index.ts
  package-lock.json
  template/config/i18n/package.json
  utils/generateIndex.ts
  utils/generateReadme.ts
Labels: enhancement

#15 Code clean up
  CONTRIBUTING.md
  index.ts
  media/screenshot-cli.png
  template/entry/default/src/main.js
  template/entry/pinia/src/main.js
  template/entry/router-and-pinia/src/main.js
  template/entry/router/src/main.js
Labels: enhancement, invalid

#17 bump up packages
  package.json
  scripts/snapshot.mjs
  template/base/package.json
  template/config/cypress-ct/package.json
  template/config/cypress/package.json
  template/config/jsx/package.json
  template/config/nightwatch/package.json
  template/config/playwright/package.json
  template/config/router/package.json
  template/config/typescript/package.json
  template/config/vitest/package.json
Labels: package update

#18 Update readme files
  README.md
  index.ts
  package.json
  utils/generateReadme.ts
Labels: documentation

#19 Update README.md
  README.md
Labels: documentation

#21 Update README.md
  README.md
Labels: documentation

#23 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#22 publish package workflow
  .github/workflows/npm-publish-package.yml
  README.md
Labels: enhancement

#26 feat: add dev command
  package-lock.json
  package.json
Labels: enhancement

#27 fix: add organization in .npmrc
  .github/workflows/npm-publish-package.yml
Labels: bug

#34 fix: generated main file formatting
  utils/generateIndex.ts
Labels: bug

#38 chore: delete prepublish command
  package.json
  scripts/prepublish.mjs
Labels: bug

#51 refactor: update information, keywords & GH url
  package.json
Labels: enhancement

#55 54 add ci badges in readmemd
  README.md
Labels: documentation

#58 refactor: normalize git url
  package.json
Labels: enhancement

#64 docs: update documentation
  README.md
Labels: documentation

#67 ci: add codeowners
  .github/CODEOWNERS
Labels: ci

#68 ci: add dependabot config
  .github/dependabot.yml
Labels: ci

#76 refactor: add contributors field
  package.json
Labels: documentation

#78 refactor: bump up package
  package.json
Labels: package update

#95 chore: update packages
  template/base/package.json
  template/config/cypress-ct/package.json
  template/config/jsx/package.json
  template/config/nightwatch-ct/package.json
  template/config/nightwatch/package.json
  template/config/pinia/package.json
  template/tsconfig/vitest/package.json
Labels: package update

#101 chore: update packages
  template/base/package.json
  template/config/cypress-ct/package.json
  template/config/cypress/package.json
  template/config/jsx/package.json
  template/config/nightwatch-ct/package.json
  template/config/pinia/package.json
  template/config/router/package.json
  template/config/typescript/package.json
  template/config/vitest/package.json
Labels: package update

#102 feat: ESLint + Prettier + Husky added by default; Switch End2End order
  index.ts
  utils/generateReadme.ts
  utils/renderEslint.ts
Labels: enhancement

#104 chore: update lockfile
  package-lock.json
  package.json
Labels: package update
