Repository MentorMate/create-vue, pull requests merged in 2023-11, with the labels that each got.

#107 Update README.md
  README.md
  utils/generateReadme.ts
Labels: documentation, refactor

#109 chore: update package version
  package.json
Labels: package update

#116 Update dependabot.yml
  .github/dependabot.yml
Labels: ci

#120 .vscode default settings & extensions
  template/base/.vscode/extensions.json
  template/base/.vscode/settings.json
  template/base/jsconfig.json
Labels: enhancement

#121 fix: added argument to include prettier in config
  utils/renderEslint.ts
Labels: bug

#122 119 prettier is missing
  package-lock.json
  package.json
Labels: package update

#133 Update gh workflows
  .github/dependabot.yml
  .github/renovate.json
Labels: ci, refactor

#140 chore: update lockfile
  package-lock.json
  package.json
Labels: package update
