Repository MentorMate/create-vue, pull requests merged in 2023-12, with the labels that each got.

#145 feat: add localization prompt
  index.ts
  locales/en-US.json
  locales/fr-FR.json
  locales/tr-TR.json
  locales/zh-CN.json
  package.json
  scripts/build.mjs
  utils/getLanguage.ts
Labels: enhancement

#151 feat: add unit tests using vitest
  .github/workflows/npm-publish-package.yml
  README.md
  __test__/getCommand.spec.ts
  __test__/locale.spec.ts
  __test__/sortDependencies.spec.ts
  package-lock.json
  package.json
  vitest.config.ts
Labels: enhancement

#161 fix: add cypress support folder to eslint overrides
  utils/renderEslint.ts
Labels: bug

#159 feat: use type=module in (most) generated projects
  index.ts
  template/base/package.json
  template/config/cypress-ct/cypress.config.js
  template/config/cypress-ct/cypress.config.ts
  template/config/cypress/cypress.config.js
  template/config/cypress/cypress.config.ts
  template/config/nightwatch/package.json
  template/config/playwright/e2e/vue.spec.js
  template/config/playwright/playwright.config.js
  template/config/playwright/playwright.config.ts
  template/tsconfig/base/tsconfig.json
  template/tsconfig/cypress-ct/tsconfig.json
  template/tsconfig/nightwatch-ct/tsconfig.json
  template/tsconfig/nightwatch/tsconfig.json
  template/tsconfig/vitest/tsconfig.json
  utils/filterList.ts
Labels: enhancement

#163 fix: prioritize enviornment variables over Intl.DateTimeFormat
  utils/getLanguage.ts
Labels: bug

#165 164 fix snapshot generation
  locales/en-US.json
  locales/fr-FR.json
  locales/zh-CN.json
  scripts/snapshot.mjs
Labels: bug

#175 174 fix vscode extensions config
  template/base/.vscode/extensions.json
  template/config/sonarQube/.vscode/extensions.json
  template/config/tailwind/.vscode/extensions.json
  template/config/typescript/.vscode/extensions.json
Labels: bug

#173 172 testing script for different combinations
  package.json
  scripts/snapshot.mjs
  scripts/test.mjs
  template/config/nightwatch/nightwatch.conf.js
  template/config/nightwatch/nightwatch/custom-assertions/elementHasCount.js
  template/config/nightwatch/nightwatch/custom-assertions/elementHasCount.ts
  template/config/nightwatch/nightwatch/custom-commands/strictClick.js
  template/config/nightwatch/nightwatch/custom-commands/strictClick.ts
  template/config/nightwatch/nightwatch/nightwatch.d.ts
  template/config/nightwatch/package.json
  template/tsconfig/base/tsconfig.node.json
Labels: bug, enhancement, good first issue

#179 154 eslint plugin for accessibility
  template/eslint/package.json
  utils/generateReadme.ts
  utils/renderEslint.ts
Labels: enhancement

#180 Update README.md
  README.md
Labels: documentation
