Repository MentorMate/create-vue, pull requests merged in 2024-03, with the labels that each got.

#217 feat: add vscode config for prettier
  index.ts
  template/base/.vscode/settings.json
  template/config/prettier/.vscode/extensions.json
  template/config/prettier/.vscode/settings.json
  utils/renderEslint.ts
Labels: enhancement

#226 feat: use Intl.getCanonicalLocales check locale
  utils/getLanguage.ts
Labels: enhancement

#227 docs: delete vue ts related information
  utils/generateReadme.ts
Labels: documentation

#225 fix: NW component testing condition
  utils/generateReadme.ts
Labels: bug, documentation

#218 feat: ci script
  .github/workflows/ci.yml
  README.md
  package-lock.json
  package.json
Labels: ci

#233 fix: get correct flags
  index.ts
Labels: bug

#232 ci: avoid double execution of ci on renovate PRs
  .github/workflows/ci.yml
Labels: ci

#234 feat: disable typescript and vitest prompts
  index.ts
Labels: enhancement

#230 ref: readme
  .gitignore
  README.md
Labels: documentation

#235 ci: remove ts and vitest feature flags
  .github/workflows/ci.yml
  scripts/snapshot.mjs
Labels: ci

#231 fix: missing --ts & --vue-router feature flags
  index.ts
Labels: bug

#241 feat: feat-eslint-vscode-settings
  index.ts
  scripts/snapshot.mjs
  template/base/.vscode/settings.json
  template/config/eslint/.vscode/extensions.json
  template/config/eslint/.vscode/settings.json
  utils/renderEslint.ts
  utils/renderTemplate.ts
Labels: enhancement

#240 fix: command description for bun
  index.ts
Labels: enhancement

#242 209 sample project structure
  .github/workflows/ci.yml
  LICENSE
  index.ts
  scripts/snapshot.mjs
  template/sample-project/.eslintrc.cjs
  template/sample-project/.gitignore
  template/sample-project/.husky/pre-commit
  template/sample-project/.prettierrc.json
  template/sample-project/.vscode/extensions.json
  template/sample-project/README.md
  template/sample-project/env.d.ts
  template/sample-project/index.html
  template/sample-project/package.json
  template/sample-project/public/favicon.ico
  template/sample-project/src/App.vue
  template/sample-project/src/assets/base.css
  template/sample-project/src/assets/logo.svg
  template/sample-project/src/assets/main.css
  template/sample-project/src/components/HelloWorld.vue
  template/sample-project/src/components/README.md
  template/sample-project/src/components/TheWelcome.vue
  template/sample-project/src/components/WelcomeItem.vue
  template/sample-project/src/components/__tests__/HelloWorld.spec.ts
  template/sample-project/src/components/icons/IconCommunity.vue
  template/sample-project/src/components/icons/IconDocumentation.vue
  template/sample-project/src/components/icons/IconEcosystem.vue
  template/sample-project/src/components/icons/IconSupport.vue
  template/sample-project/src/components/icons/IconTooling.vue
  template/sample-project/src/main.ts
  template/sample-project/src/router/index.ts
  template/sample-project/src/stores/sample-project-store.ts
  template/sample-project/src/views/AboutView.vue
  template/sample-project/src/views/HomeView.vue
  template/sample-project/src/views/README.md
  template/sample-project/tsconfig.app.json
  template/sample-project/tsconfig.json
  template/sample-project/tsconfig.node.json
  template/sample-project/tsconfig.vitest.json
  template/sample-project/vite.config.ts
  template/sample-project/vitest.config.ts
Labels: enhancement
