Repository MentorMate/create-vue, pull requests merged in 2024-02, with the labels that each got.

#198 Create auto-assign.yml
  .github/auto-assign.yml
Labels: enhancement, ci

#197 Remove redundant @types/nightwatch
  package.json
  template/config/nightwatch/package.json
Labels: package update

#201 185 eslint plugin playwright
  utils/renderEslint.ts
Labels: enhancement

#205 Create components README.md
  package-lock.json
  template/base/src/components/README.md
Labels: documentation

#212 feat: add vite devtools plugin
  template/base/package.json
  template/base/vite.config.js.data.mjs
Labels: enhancement

#211 doc:routes views structure
  template/config/router/src/views/README.md
Labels: documentation

#215 refactor: change minimist to parseArgs
  index.ts
  package-lock.json
  package.json
Labels: refactor
