Repository MentorMate/create-vue, pull requests merged in 2024-01, with the labels that each got.

#187 feat(pull_request): create Pull request template
  .github/pull_request_template.md
Labels: enhancement, ci

#186 chore: update playwright config & ts config
  template/config/playwright/playwright.config.js
  template/tsconfig/base/tsconfig.app.json
  template/tsconfig/base/tsconfig.node.json
  template/tsconfig/cypress-ct/tsconfig.cypress-ct.json
  template/tsconfig/nightwatch-ct/tsconfig.app.json
  template/tsconfig/nightwatch/nightwatch/tsconfig.json
  template/tsconfig/vitest/tsconfig.vitest.json
Labels: bug, enhancement

#188 feat: add support for eslint-plugin-playwright
  index.ts
  template/eslint/package.json
  utils/renderEslint.ts
Labels: enhancement

#194 Upgrade @tsconfig/node20
  package.json
  template/tsconfig/base/package.json
  template/tsconfig/base/tsconfig.node.json
  template/tsconfig/nightwatch/nightwatch/tsconfig.json
  template/tsconfig/playwright/e2e/tsconfig.json
  tsconfig.json
Labels: package update

#196 Update locale setup
  locales/zh-Hans.json
  locales/zh-Hant.json
  utils/getLanguage.ts
Labels: enhancement

#195 Upgrade husky
  .husky/commit-msg
  .husky/pre-commit
  .husky/prepare-commit-msg
  package.json
  template/config/husky/.husky/pre-commit
  template/config/husky/package.json
Labels: package update
